The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/net/tscratch/people/plgas2000/.conda/envs/env_zzsn/lib/python3.9/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "/net/tscratch/people/plgas2000/zzsn-project/scripts/train/train_dreambooth_lora_sdxl.py", line 52, in <module>
    from diffusers import (
ImportError: cannot import name 'EDMEulerScheduler' from 'diffusers' (/net/tscratch/people/plgas2000/.conda/envs/env_zzsn/lib/python3.9/site-packages/diffusers/__init__.py)
Traceback (most recent call last):
  File "/net/tscratch/people/plgas2000/.conda/envs/env_zzsn/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/net/tscratch/people/plgas2000/.conda/envs/env_zzsn/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/net/tscratch/people/plgas2000/.conda/envs/env_zzsn/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1075, in launch_command
    simple_launcher(args)
  File "/net/tscratch/people/plgas2000/.conda/envs/env_zzsn/lib/python3.9/site-packages/accelerate/commands/launch.py", line 681, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/net/tscratch/people/plgas2000/.conda/envs/env_zzsn/bin/python', 'scripts/train/train_dreambooth_lora_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--instance_data_dir=./dataset/dreambooth-main/dataset/dog3', '--output_dir=./models/dreambooth_lora_sdxl_dog3_subject_2024-05-27_18-44-59', '--class_data_dir=./dataset/dreambooth_generated/dog', '--class_prompt=a photo of a dog', '--instance_prompt=a photo of sks dog', '--resolution=1024', '--with_prior_preservation', '--prior_loss_weight=0.1', '--train_batch_size=1', '--learning_rate=5e-5', '--report_to=tensorboard', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=800', '--validation_prompt=a photo of sks dog in a bucket', '--validation_epochs=50', '--mixed_precision=fp16', '--enable_xformers_memory_efficient_attention', '--logging_dir=./logs/tensorboard_logs', '--gradient_checkpointing', '--use_8bit_adam']' returned non-zero exit status 1.
