The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "/net/tscratch/people/plgas2000/zzsn-project/scripts/train/train_dreambooth_ziplora_sdxl.py", line 62, in <module>
    from ziplora_pytorch import ZipLoRALinearLayer
ModuleNotFoundError: No module named 'ziplora_pytorch'
Traceback (most recent call last):
  File "/net/tscratch/people/plgas2000/.conda/envs/env_zzsn/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/net/people/plgrid/plgas2000/.local/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/net/people/plgrid/plgas2000/.local/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1075, in launch_command
    simple_launcher(args)
  File "/net/people/plgrid/plgas2000/.local/lib/python3.9/site-packages/accelerate/commands/launch.py", line 681, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/net/tscratch/people/plgas2000/.conda/envs/env_zzsn/bin/python', 'scripts/train/train_dreambooth_ziplora_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--output_dir=./models/ziplora_dog3_style1_cartoon_2024-05-27_00-37-51', '--lora_name_or_path=./models/dreambooth_lora_sdxl_dog3_2024-05-24_23-43-20', '--instance_prompt=a photo of sks dog', '--instance_data_dir=./dataset/dreambooth-main/dataset/dog3', '--lora_name_or_path_2=./models/dreambooth_lora_sdxl_style1_cartoon_2024-05-26_23-37-49', '--instance_prompt_2=a cat of in crt style', '--instance_data_dir_2=./dataset/styles/style1-cartoon', '--resolution=1024', '--train_batch_size=1', '--learning_rate=5e-5', '--similarity_lambda=0.01', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=100', '--validation_prompt=a photo of sks dog in crt style', '--validation_epochs=10', '--mixed_precision=fp16', '--report_to=tensorboard', '--enable_xformers_memory_efficient_attention', '--logging_dir=./logs/tensorboard_logs']' returned non-zero exit status 1.
